# https://github.com/zerostaticthemes/jekyll-serif-theme#github-pages
# baseurl: "/jekyll-in-2023-lol/"

collections:
  authors:
    output: true

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: "blog"
      type: "pages"
    values:
      layout: "blog"
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-github-metadata

# environment: production # overrides jekyll.environment which is the default
